apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-time-exercise
  namespace: liatrio-time-exercise-namespace
  labels:
    app: liatrio-time-exercise
spec:
  replicas: 3
  selector:
    matchLabels:
      app: liatrio-time-exercise
  template:
    metadata:
      labels:
        app: liatrio-time-exercise
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: liatrio-time-exercise
          image: 798870450882.dkr.ecr.us-east-1.amazonaws.com/liatrio-exercise-repo:latest 
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
